accounts/urls.py
from os import name
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('register/', views.register, name='register'),
]

app_car/urls.py
from django.urls import path
from . import views

app_name = 'app_car'

urlpatterns = [
    path('', views.home, name="home"),
    path('cars/', views.cars, name='cars'),
    path('details/<str:slug>/', views.details, name="details"),
    path('details_id/<int:id>/', views.details_id, name="details_id"),
    path('random-cars/', views.random_cars, name="random"),
    path('add_car/', views.add_car, name='AddCar'),
    path('edit/<str:slug>/', views.edit_car, name='EditCar'),
]

project_car/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_car.urls', namespace='app_car')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_image_path,image_size,CHOICES_LIST
from django_jalali.db import models as jmodels

# Create your models here.

class Log(models.Model):
    created = jmodels.jDateTimeField(auto_now_add=True)
    description = models.TextField()

class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name="کاربر", on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(verbose_name="درباره من", null=True, blank=True)
    phone = models.CharField(verbose_name="شماره همراه", max_length=11, null=True, blank=True, help_text="شماره همراه با صفر وارد شود")
    avatar = models.ImageField(verbose_name="تصویر کاربر", upload_to=get_image_path, validators=[image_size])
    gender = models.CharField(verbose_name="جنسیت", max_length=10, choices=CHOICES_LIST)
    nc = models.CharField(verbose_name="کدملی", max_length=10, null=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Profile
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label="username", label_suffix="", widget=forms.TextInput(attrs={
        'class':'input100','placeholder':'نام کاربری را وارد نمایید', 'title':''
    }))
    password = forms.CharField(label="password", label_suffix="", widget=forms.PasswordInput(attrs={
        'class':'input100','placeholder':'کلمه عبور را وارد نمایید', 'title':''}))


class ProfileForm(forms.ModelForm):
    # username = forms.CharField(label='نام کاربری')
    # password = forms.CharField(label='کلمه عبور', widget=forms.PasswordInput)
    bio = forms.CharField(label='درباره من', required=False)
    class Meta:
        model=User
        fields=['username','first_name', 'last_name', 'email']
        labels={}
        help_texts={'username':"",}
    
    # def clean_username(self):
    #     data = self.cleaned_data["username"]
    #     if len(data) < 5:
    #         self.add_error('username', 'نام کاربری می بایست بیشتر از 5 حرف باشد')
    #     return data
    

accounts/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.

from django import forms
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import LoginForm,ProfileForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

# def login_view(request):
#     template_name = "accounts/login.html"
#     context={}

#     if request.method=="POST":
#         username = request.POST['username']
#         password = request.POST['password']

#         if not User.objects.filter(username=username).exists():
#          messages.success(request, "user")
#          context['user_not_found'] = True
#          return render(request,template_name, context)

#         user = authenticate(username=username, password=password)
#         if user is not None:
#             login(request, user)
#             messages.success(request, "you are login successfully")
#             return redirect('blog:home')
#         else:
#             context['error']=True
#             return render(request, template_name, context)

#     return render(request, template_name, context)
# def login_view(request):
#     template_name = "accounts/login.html"
#     context={}
#     if request.method=='POST':
#         username = request.POST.get('username')
#         password = request.POST.get('pass')
#         if not User.objects.filter(username=username).exists():
#             messages.warning(request, "چنین کاربری وجود ندارد")
#             return render(request, template_name, context)

#         user = authenticate(username=username, password=password)
#         if user is not None:
#             print("<<<<<<>>>>>>>",request.POST)
#             login(request, user)
#             messages.success(request,"شما با موفقیت وارد شدید")
#             return redirect("blog:home")
#         else:
#             messages.error(request, "نام کاربری و یا کلمه عبور اشتباه می باشد")
#             return render(request, template_name, context)

#     return render(request, template_name, context)

def login_view(request):
    template_name = "accounts/login.html"
    form = LoginForm()
    context = {'form':form}
    if request.method=="POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            if not User.objects.filter(username=username).exists():
                messages.warning(request, 'چنین کابری وجود ندارد')
                return render(request, template_name, context)
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "شما با موفقیت وارد شدید")
                return redirect('app_car:home')
            else:
                messages.info(request,'نام کاربری و یا کلمه عبور صحیح نمی باشد')
                return render(request, template_name, context)
        else:
            messages.error(request, "مشکلی وجود دارد...")

    
    return render(request, template_name, context)

def logout_view(request):
    logout(request)
    messages.success(request, 'با آرزوی دیدار مجدد شما کاربر عزیز')
    return redirect("accounts:login")

@login_required
def profile_view(request):
    template_name = 'accounts/profile.html'
    context = {}
    user = request.user
    initial = {
        'bio': user.profile.bio
        }
    form = ProfileForm(request.POST or None, instance=user, initial=initial)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            bio = form.cleaned_data['bio']
            user.profile.bio = bio
            user.profile.save()
            messages.success(request, 'تغییرات کاربری انجام شد')
            return redirect('accounts:profile')
        else:
            context={'form':form}
            return render(request, template_name, context)

    context={'form':form}
    return render(request, template_name, context)


def register(request):
    template_name = 'accounts/register.html'
    context={}
    form = UserCreationForm(request.POST or None)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.success(request,"ثبت نام شد با موفقیت انجام شد")
            return redirect("accounts:login")
        else:
            context['form']=form
            return render(request, template_name, context)
    else:
        context['form']=form
       
    return render(request, template_name, context)

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>ورود به بلاگ</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body style="background-color: #666666;">
{% include 'navbar.html' %}
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST">
				{% csrf_token %}
					<span class="login100-form-title p-b-43">
						Login to website
					</span>
					{% if messages %}
						{% for message in messages %}
						<div class="{{message.tags}} alert-dismissible fade show" role="alert">
						{{message}}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						</button>
						</div>						
						{% endfor %}
					{% endif %}

					<div class="wrap-input100 validate-input" data-validate = "Valid username is required">
						{{form.username}}
						<span class="focus-input100"></span>
						<span class="label-input100">Username</span>
					</div>
					
					
					<div class="wrap-input100 validate-input" data-validate="Password is required">
						{{form.password}}
						<span class="focus-input100"></span>
						<span class="label-input100">Password</span>
					</div>

					<div class="flex-sb-m w-full p-t-3 p-b-32">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="#" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>
			

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
					
					<div class="text-center p-t-46 p-b-20">
						<span class="txt2">
							or sign up using
						</span>
					</div>

					<div class="login100-form-social flex-c-m">
						<a href="{% url 'accounts:register' %}" class="login100-form-social-item flex-c-m bg1 m-r-5">
							<i class="fa fa-facebook-f" aria-hidden="true"></i>
						</a>

						<a href="#" class="login100-form-social-item flex-c-m bg2 m-r-5">
							<i class="fa fa-twitter" aria-hidden="true"></i>
						</a>
					</div>
				</form>

				<div class="login100-more" style="background-image: url('{% static 'login/images/bg-01.jpg' %}');">
				</div>
			</div>
		</div>
	</div>
	
	

	
	
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Profile{% endblock title %}
{% block content %}
<form action='.' method='POST' class='form-group form-control-lg'>
{% csrf_token %}
  {{form|crispy}}

  <button type="submit" class="btn btn-primary mt-2">ذخیره</button>
</form>

{% endblock content %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>ثبت نام</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body style="background-color: #666666;">
{% include 'navbar.html' %}
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST">
				{% csrf_token %}
					<span class="login100-form-title p-b-43">
						ثبت نام در سایت
					</span>

                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                <strong>{{ field.label }}:&nbsp;</strong><span>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endif %}

					<div class="wrap-input100 validate-input" data-validate = "Valid username is required">
						<input class="input100" type="text" name="username" value={{request.POST.username}}>
						<span class="focus-input100"></span>
						<span class="label-input100">Username</span>
					</div>
					
					
					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="pass">
						<span class="focus-input100"></span>
						<span class="label-input100">Password</span>
					</div>

					<div class="flex-sb-m w-full p-t-3 p-b-32">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="#" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>
			

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
					
					<div class="text-center p-t-46 p-b-20">
						<span class="txt2">
							or sign up using
						</span>
					</div>

					<div class="login100-form-social flex-c-m">
						<a href="#" class="login100-form-social-item flex-c-m bg1 m-r-5">
							<i class="fa fa-facebook-f" aria-hidden="true"></i>
						</a>

						<a href="#" class="login100-form-social-item flex-c-m bg2 m-r-5">
							<i class="fa fa-twitter" aria-hidden="true"></i>
						</a>
					</div>
				</form>

				<div class="login100-more" style="background-image: url('{% static 'login/images/bg-01.jpg' %}');">
				</div>
			</div>
		</div>
	</div>
	
	

	
	
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>