app_car/urls.py
from django.urls import path
from . import views

app_name = 'app_car'

urlpatterns = [
    path('', views.home, name="home"),
    path('cars/', views.cars, name='cars'),
    path('details/<str:slug>/', views.details, name="details"),
    path('details_id/<int:id>/', views.details_id, name="details_id"),
    path('random-cars/', views.random_cars, name="random"),
    path('add_car/', views.add_car, name='AddCar'),
    path('edit/<str:slug>/', views.edit_car, name='EditCar'),
]

project_car/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_car.urls', namespace='app_car')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_car/models.py
from re import T
from django.db import models
from .utils import path_car,LIST_STATUS,OFFICIAL, validat_image
from django.utils.text import slugify
from django_jalali.db import models as jmodels
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Car(models.Model):
    slug = models.SlugField(verbose_name="پیوند یکتا", null=True, blank=True, allow_unicode=True)
    code = models.PositiveSmallIntegerField(verbose_name="کد خودرو", null=True, unique=True, blank=True)
    name = models.CharField(max_length=30, verbose_name="نام خودرو", null=True)
    company = models.ForeignKey("Company", verbose_name="نام برند", on_delete=models.SET_NULL, null=True, blank=True,\
    related_name='cars')
    agency = models.ForeignKey("Agency", verbose_name="نام نمایندگی", on_delete=models.CASCADE,\
    related_name='cars')
    created_at = jmodels.jDateTimeField(verbose_name="تاریخ ثبت",auto_now_add=True, null=True, blank=True )
    year = models.PositiveSmallIntegerField(verbose_name="سال تولید", null=True)
    price = models.PositiveBigIntegerField(verbose_name="قیمت", null=True)
    stock = models.BooleanField(verbose_name="موجود", default=True ,help_text="در صورت موجود بودن علامت کنار آن قابل مشاهده است")
    image = models.ImageField(verbose_name="تصویر خودرو", upload_to =path_car, validators=[validat_image])
    descript = models.TextField(verbose_name="توضیحات",null=True, blank=True)

    def save(self,*args,**kwrags):
        self.slug = slugify(self.name, allow_unicode=True)
        self.code = self.id
        super().save(*args,**kwrags)
    
    def get_date(self):
        return self.created_at.strftime('%H:%m -- %Y/%m/%d')
    get_date.short_description="تاریخ ثبت"

    def get_image(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" alt="{self.name}" width="150" height="100">')
        else:
            return mark_safe('<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsNGGjrfSqqv8UjL18xS4YypbK-q7po_8oVQ&usqp=CAU" width="100" height="100">')
    get_image.short_description = 'عکس خودرو'

    class Meta:
        verbose_name = "نام خودرو"
        verbose_name_plural = "نام خودروها"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("app_car:details", kwargs={"slug": self.slug})
    


class Company(models.Model):
    name = models.CharField(max_length=50, verbose_name="نام برند", null=True)
    country = models.CharField(max_length=30, verbose_name="نام کشور تولید کننده", null=True)
    introduction = models.TextField(verbose_name="معرفی برند" ,null=True, blank=True)


    class Meta:
        verbose_name = "نام برند"
        verbose_name_plural = "نام  برندها"

    def __str__(self):
        return self.name


class Agency(models.Model):
    name = models.CharField(max_length=50, verbose_name="نام نمایندگی", null=True)
    code = models.CharField(max_length=10, verbose_name="کد نمایندگی", null=True)
    phone = models.CharField(max_length=11, verbose_name="شماره تماس", null=True)
    status = models.CharField(max_length=10, choices=LIST_STATUS, default=OFFICIAL)
    address = models.TextField(null=True)
    url_site = models.URLField()


    class Meta:
        verbose_name = "نام نمایندگی"
        verbose_name_plural = "نام نمایندگی ها"

    def __str__(self):
        return self.name

app_car/forms.py
from django import forms
from django.forms import ModelForm
from .models import Car


class CarForm(ModelForm):

    class Meta:
        model = Car
        exclude = ['slug','code','created_at']


class EditCarForm(ModelForm):

    class Meta:
        model = Car
        exclude = ['slug','code','created_at']

app_car/views.py
import re
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Car, Company, Agency
import random
from django.db.models import Count
from .forms import CarForm,EditCarForm
from django.contrib import messages

# Create your views here.


def home(request):
    search = False
    if request.is_ajax():
        search = True
        value_search = request.GET.get('search_text', None)
        if value_search:
            cars = Car.objects.filter(name__contains=value_search)
            context = {
                'cars':cars,
                'search':search,
            }
            return render(request, 'app_car/search_results.html', context)
    if request.method =="GET":
            search =True
            value_search = request.GET.get('search', None)
            if value_search:
                cars = Car.objects.filter(name__contains=value_search)
                context={
                    'cars':cars,
                    'search':search,
                }
                return render(request, 'app_car/home.html', context)

    return render(request,'app_car/home.html')

#-------------- get all cars --------------#
def cars(request):
    template_cars = 'app_car/cars.html'
    all_cars = Car.objects.all().order_by('-price')
    context = {
        'cars':all_cars
    }
    return render(request, template_cars, context)

#-------------- get car with slug --------------#
def details(request,slug):
    car = get_object_or_404(Car, slug=slug)
    context = {
        "car":car
    }
    return render(request, 'app_car/details.html', context)

#-------------- get car with code --------------#
def details_id(request,id):
    car = get_object_or_404(Car, code=id)
    status = car.stock
    context = {
        "car":car, "status":status
    }
    return render(request, 'app_car/details.html', context)

#-------------- get car randomly --------------#
def random_cars(request):
    nums = Car.objects.all().aggregate(numbers = Count('id'))
    print(nums)
    ran = (random.randint(0, nums['numbers']))-1
    my_car = get_object_or_404(Car, id=ran)
    context = {
        "my_car":my_car
    }
    return render(request, 'app_car/random_cars.html', context)

def add_car(request):
    template_name = 'app_car/add_car.html'
    form = CarForm(request.POST or None, request.FILES or None)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.success(request,'ماشین جدید با موفقیت اضافه گردید')
            return redirect('app_car:home')
    else:
        context={'form':form}
    return render(request, template_name,context)

def edit_car(request, slug):
    template_name = 'app_car/edit_car.html'
    car = get_object_or_404(Car, slug=slug)
    form = EditCarForm(request.POST or None, request.FILES or None, instance=car)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'ماشین مورد نظر اصلاح گردید')
            return redirect('app_car:home')
    else:
        context={'form':form}
    return render(request,template_name, context )

app_car/templates/app_car/add_car.html
{% extends 'base.html' %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block title %} Add Car {% endblock title %}
{% block content %}
<form class="login100-form validate-form" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {{form|crispy}}
</from>
{% endblock content %}

app_car/templates/app_car/cars.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} MyCars {% endblock title %}
{% block content %}
<a href={% url 'app_car:random' %} type="button" class="btn btn-primary btn-lg btn-block my-2">انتخاب تصادفی ماشین</a>
{% for car in cars%}
<div class="card d-inline-block mb-3" style="width: 22.92rem;">
    <img src="{{car.image.url}}" class="card-img-top" alt="{{car.name}}" width="150" height="200">
    <div class="card-body">
        {% if forloop.last %}
            <h5 class="card-title text-danger">مدل{{car.year}}-{{car.name}}</h5>
        {% elif forloop.counter == 3 %}
            <h5 class="card-title text-success">مدل{{car.year}}-{{car.name}}</h5>
        {% else %}
            <h5 class="card-title">مدل{{car.year}}-{{car.name}}</h5>
        {% endif %}
    </div>
    <ul class="list-group list-group-flush">
        <!-- <li class="list-group-item">سال تولید: {{car.year}}</li> -->
        <li class="list-group-item">قیمت :{{car.price|intword}} ریال</li>
        <li class="list-group-item">ثبت :{{car.get_date}}</li>
    </ul>
    <div class="card-body">
        {% if car.stock %}
        <a href="{% url 'app_car:details_id' car.id %}" class="btn btn-info">توضیحات بیشتر</a>
        <a href="https://web.whatsapp.com/send?text={{ request.build_absolute_uri }}{% url 'app_car:details' car.slug %}" data-action="share/whatsapp/share" target="_blank" class="btn btn-success">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share-fill" viewBox="0 0 16 16">
                <path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5z"/>
              </svg></a>
        {% else %}
        <a href="#" class="btn btn-light disabled">موجود نمی باشد</a>
        <a href="#" class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share-fill" viewBox="0 0 16 16">
                <path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5z"/>
              </svg></a>
        {% endif %}
    </div>
</div>
{% endfor %} {% endblock content%}

app_car/templates/app_car/details.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <img src="{{car.image.url}}" class="rounded mx-auto d-block my-3" alt="Responsive image">
  <div class="list-group">
  <li class="list-group-item list-group-item-action active d-flex">
توضیحات تکمیلی  </li>
  <li class="list-group-item list-group-item-action mt-0 d-flex mr-0">نام: {{car.name}}</li>
  <li class="list-group-item list-group-item-action mt-0 d-flex mr-0">برند: {{car.company}}</li>
  <li class="list-group-item list-group-item-action mt-0 d-flex mr-0">نمایندگی: {{car.agency}}</li>
  <li class="list-group-item list-group-item-action mt-0 d-flex mr-0">سال تولید: {{car.year}}</li>
  <li class="list-group-item list-group-item-action mt-0 d-flex mr-0">قیمت: {{car.price|floatformat:1|intcomma}} ریال</li>
<div class="media-body text-justify">
    <h5 class="mt-3 d-flex mr-3">شرح حال خودرو</h5>
    <p class="mt-3 d-flex mr-3">{{car.descript}}</p>
  </div>
  <a href="{% url 'app_car:EditCar' car.slug %}" class="btn btn-info">اصلاح مشخصات ماشین</a>
{% endblock content %}

app_car/templates/app_car/edit_car.html
{% extends 'base.html' %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block title %} Edit Car {% endblock title %}
{% block content %}
<form class="login100-form validate-form" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {{form|crispy}}
</from>
{% endblock content %}

app_car/templates/app_car/home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Car exhibition{% endblock title%}

{% block content %}
<form class="d-flex" action="." method="GET">
<input class="form-control me-2" type="search" placeholder="جستجو" aria-label="Search" name="search" id="search" value="{{request.GET.search}}">
<button class="btn btn-outline-success mr-3" type="submit">جستجو</button>
</form>
{% include 'app_car/search_results.html' %}
<div class="card d-flex mt-1">
  <div class="card-body">
    <h5 class="card-title text-justify">به نمایشگاه ماشین مهدی خوش آمدید</h5>
    <p class="card-text text-justify">شما میتوانید در این نمایشگاه ماشین مورد نظر خود را جستجو کنید و در صورت تمایل اقدام به خرید آن نمایید</p>
  </div>
</div>
<div class="media">
    <img src="{% static 'images/car.jpg' %}" width="100%" height="400" class="mt-1" alt="Car exhibition">
</div>
{% endblock content%}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/search-ajax.js' %}"></script>
{% endblock js %}

app_car/templates/app_car/random_cars.html
{% extends 'base.html' %}
{% block content %}
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{my_car.image.url}}" class="card-img-top" alt="{{my_car.name}}" width="150" height="200" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{my_car.name}}</h5>
    <p class="card-text mt-3 d-flex mr-3 text-justify">{{my_car.descript}}</p>
    <a href={% url 'app_car:cars' %} class="btn btn-primary">بازگشت به ماشین ها</a>
  </div>
</div>   

{% endblock content %}

app_car/templates/app_car/search_results.html
{% load humanize %}
<div class="card" id="self_result">
{% if cars %}
{% for car in cars %}
  <div class="card-header d-flex">
    مدل{{car.year}}-{{car.name}}
  </div>
  <div class="card-body d-flex">
    <h5 class="card-title">قیمت :{{car.price|intword}} ریال</h5>
    <a href="{{car.get_absolute_url}}" class="btn btn-success">جزِئیات بیشتر</a>
  </div>
</div>
{% endfor %}
<a href="/" class="btn btn-primary"> پاک کردن نتیجه جستجو </a>
{% elif request.GET.search or search %}
  <div class="card-header d-flex">
    متاسفانه این ماشین وجود ندارد
  </div>
  <a href="/" class="btn btn-primary"> پاک کردن نتیجه جستجو </a>
{% endif %}
</div>