accounts/urls.py
from os import name
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('register/', views.register, name='register'),
]

app_car/urls.py
from django.urls import path
from . import views

app_name = 'app_car'

urlpatterns = [
    path('', views.home, name="home"),
    path('cars/', views.cars, name='cars'),
    path('details/<str:slug>/', views.details, name="details"),
    path('details_id/<int:id>/', views.details_id, name="details_id"),
    path('random-cars/', views.random_cars, name="random"),
    path('add_car/', views.add_car, name='AddCar'),
    path('edit/<str:slug>/', views.edit_car, name='EditCar'),
]

project_car/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_car.urls', namespace='app_car')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}{% endblock css %}

</head>

<body>
    {% include 'navbar.html' %}
    <div class="container mx-auto my-sm-5">
        {% block content %}{% endblock content%}
    </div>

    {% if messages %}
  {% for message in messages %}  
    <div class="{{message.tags}} alert-dismissible fade show" role="alert">
						{{message}}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						</button>
		</div>
  {% endfor %}
{% endif %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper)
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    -->

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% block js %}
    {% endblock js %}

</body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-info">
    <span class="border border-primary"></span>
    <div class="container-fluid">
        {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="/">
            <img class="rounded-circle  border border-danger" src="{% static 'images/car-exhibition.jpg' %}" width="100" height="100" alt="نمایشگاه ماشین مهدی"> خوش آمدید {{request.user.first_name}} عزیز
        </a>
        {% else %}
        <a class="navbar-brand" href="/">
            <img class="rounded-circle" src="{% static 'images/car-exhibition.jpg' %}" width="100" height="100" alt="نمایشگاه ماشین مهدی">
        </a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active ml-1 border-bottom border-dark">
                    <a class="nav-link btn btn-light" aria-current="page" href="/">خانه</a>
                </li>
                <li class="nav-item ml-1 border-bottom border-dark">
                    <a class="nav-link btn btn-light" href="{% url 'app_car:cars' %}">خودروها</a>
                </li>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                         <li class="nav-item ml-1 border-bottom border-dark">
                            <a class="nav-link btn btn-light" target="_blank" href={% url 'admin:index' %}>پنل مدیریت</a>
                        </li>
                    {% endif %}
                <li class="nav-item ml-1 border-bottom border-dark">
                    <a class="nav-link btn btn-light" href="{% url 'app_car:AddCar' %}">اضافه کردن ماشین</a>
                </li>
                <li class="nav-item ml-1 border-bottom border-dark">
                    <a class="nav-link btn btn-light" href="{% url 'accounts:profile' %}">پروفایل</a>
                </li>
                <li class="nav-item ml-1 border-bottom border-info">
                    <a class="nav-link text-danger btn btn-light" href="{% url 'accounts:logout' %}">خروج</a>
                </li>
                {% else %}
                <li class="nav-item ml-1 border-bottom border-info">
                    <a class="nav-link btn btn-light" href="{% url 'accounts:login' %}">ورود</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>